# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPlainTextEdit, QLabel


class Ui_ADDWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 314)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.variety = QPlainTextEdit(self)
        self.variety.move(111, 10)
        self.variety.resize(281, 31)
        self.roasting = QPlainTextEdit(self)
        self.roasting.move(111, 50)
        self.roasting.resize(281, 31)
        self.ground_or_grains = QPlainTextEdit(self)
        self.ground_or_grains.move(111, 90)
        self.ground_or_grains.resize(281, 31)
        self.taste = QPlainTextEdit(self)
        self.taste.move(111, 130)
        self.taste.resize(281, 31)
        self.price = QPlainTextEdit(self)
        self.price.move(111, 170)
        self.price.resize(281, 31)
        self.volume = QPlainTextEdit(self)
        self.volume.move(111, 210)
        self.volume.resize(281, 31)
        self.label = QLabel('Сорт', self)
        self.label.move(10, 10)
        self.label.resize(81, 31)
        self.label_2 = QLabel('Степень обжарки', self)
        self.label_2.move(10, 50)
        self.label_2.resize(101, 31)
        self.label_3 = QLabel('Молотый/ в зернах', self)
        self.label_3.move(10, 90)
        self.label_3.resize(101, 31)
        self.label_4 = QLabel('Цена', self)
        self.label_4.move(10, 170)
        self.label_4.resize(81, 31)
        self.label_5 = QLabel('Объем', self)
        self.label_5.move(10, 210)
        self.label_5.resize(81, 31)
        self.label_6 = QLabel('Вкус', self)
        self.label_6.move(10, 130)
        self.label_6.resize(81, 31)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 250, 141, 41))
        self.pushButton.setObjectName("Добавить")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 683, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Добавить"))
        self.pushButton.setText(_translate("MainWindow", "Добавить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    UI = Ui_ADDWindow()
    UI.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())